### PR TITLE
iOS Mapbox GeoJson Review

### PR DESCRIPTION
**Pull request by WillMahler**

### CODE REVIEW

**Review by dellisd — APPROVED** [review]

**Review by ghaskins99 — APPROVED** [review]

**Comment by dellisd** [comment]
Tbh idk how to undo an approved PR, but this will still need the memory cleanup fixes before merging.

**Review by dellisd — CHANGES_REQUESTED** [review]
The allocated arrays _will_ need to be cleaned up, but only within the scope of the GeoJsonExtensions file.

**Comment by WillMahler** [comment]
Sounds good, I wondered about that when I saw that you approved it lol. I'll work on that later and push another commit for it.

**Comment by dellisd** [comment]
```kotlin
@with<NativePlacement>
internal fun List<Position>.toCoreLocation() = allocArray<CLLocationCoordinate2D>(size) { index ->
        fromPosition(this[index])
    }
```
This would have been a great usecase for the proposed multiple receivers feature :eyes:
too bad it's not available yet

**Review by dellisd — APPROVED** [review]

**Pull request merged**
